### ISSUE TITLE
Typescript: `use` method not defined for fastify instance

### ISSUE THREAD

**Issue by stephan9mertel** [fastify/help#487]
I'm using fastify with typescript and implement a middleware according to https://www.fastify.io/docs/latest/Middleware/.
However, when I pass my middleware to the fastify instance's use method, typescript tells me that there is no such method defined: `Property 'use' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'`

My code:
```ts
    const server = fastify(serverOpts);
    await server.register(require("middie"));
    server.use(fastifyTracingMiddleware(tracer, ["/"]));  // <-- Here is where it fails
```
What I do for now is to use the "as any" trick:
```ts
(server as any).use(fastifyTracingMiddleware(tracer, ["/"]));
```
But that is bad practise...

- *node version*: 14
- *fastify version*: 3.18.1
- *os*: Linux

**Comment by kibertoad** [comment]
Why are you using `use` instead of `register`?

**Comment by climba03003** [comment]
There is no import of type when you use `require('middle')`. and that is the reason type merging will not works.

**Comment by stephan9mertel** [comment]
@kibertoad because this is how it is supposed to use according to https://github.com/fastify/middie, isn't it?

@climba03003 I changed my code to
```ts
import middie from "middie";
const server = fastify(serverOpts);
await server.register(middie);
server.use(fastifyTracingMiddleware(tracer, ["/"]));
```
Works perfectly, thanks a lot!
