### ISSUE TITLE
A change in Fastify hook types broke our hooks

### ISSUE THREAD

**Issue by anttti** [fastify/help#603]
## 💬  A change in Fastify hook types broke our hooks

When upgrading Fastify we encountered strange problems with our `preHandler`-hooks. Narrowing down, the problem was introduced when upgrading from 3.18.0 to 3.18.1, and more specifically it was this change: https://github.com/fastify/fastify/pull/3143/files

Given a custom hook
```ts
// A hook that does nothing, just to demonstrate the issue with the types
const myHook: preHandlerAsyncHookHandler<
  RawServerBase,
  RawRequestDefaultExpression<RawServerBase>,
  RawReplyDefaultExpression<RawServerBase>,
  {}
> = async (_req, _res) => undefined;
```

and using it like this
```ts
interface TestRoute extends RouteGenericInterface {
  readonly Reply: { ok: boolean };
}

const testRoutes: FastifyPluginAsync = (instance) => {
  instance.addHook("preHandler", myHook);

  instance.route<TestRoute>({
    method: "GET",
    url: "/",
    handler: async (_req, res) => res.send({ ok: true }),
  });

  return Promise.resolve();
};
```

we get this error
```
src/testRoutes.ts:27:20 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"preHandler"' is not assignable to parameter of type '"onClose"'.

27   instance.addHook("preHandler", myHook);
                      ~~~~~~~~~~~~

  node_modules/fastify/types/instance.d.ts:307:3
    307   addHook(
          ~~~~~~~~
    308     name: 'onClose',
        ~~~~~~~~~~~~~~~~~~~~
    309     hook: onCloseHookHandler<RawServer, RawRequest, RawReply, Logger>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    310   ): FastifyInstance<RawServer, RawRequest, RawReply, Logger>;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

I set up a minimal project demonstrating just this issue: https://github.com/anttti/fastify-types

Just run `yarn && yarn build` to see the error. 

What are we doing wrong?

## Your Environment

- *node version*: 14.15.4
- *fastify version*: 3.18.1 and onwards
- *os*: Mac, but issue seems to be platform independent

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by darkgl0w** [comment]
Thank you for reporting this with a reproducible example @anttti 👍 

I tried to define the `preHandler` hook in the shorthand route option like this and it highlighted more unwanted breaking changes introduced by the aforementioned PR.
```ts
import type {
  FastifyPluginAsync,
  preHandlerAsyncHookHandler,
  RawReplyDefaultExpression,
  RawRequestDefaultExpression,
  RawServerBase,
} from "fastify";
import { RouteGenericInterface } from "fastify/types/route";

interface TestRoute extends RouteGenericInterface {
  readonly Reply: { ok: boolean };
}

// A hook that does nothing, just to demonstrate the issue with the types
const myHook: preHandlerAsyncHookHandler<
  RawServerBase,
  RawRequestDefaultExpression<RawServerBase>,
  RawReplyDefaultExpression<RawServerBase>,
  {}
> = async (_req, _res) => undefined;

const testRoutes: FastifyPluginAsync = (instance) => {
  // An error here:
  // No overload matches this call.
  //   The last overload gave the following error.
  //     Argument of type '"preHandler"' is not assignable to parameter of type '"onClose"'.
  instance.addHook("preHandler", myHook);

  instance.route<TestRoute>({
    method: "GET",
    url: "/",
    preHandler: myHook, // will trigger the error below
    handler: async (_req, res) => res.send({ ok: true }),
  });

  return Promise.resolve();
};

export default testRoutes;

```
Here is the error I got from typescript :
```ts
(property) RouteShorthandOptions<Server, IncomingMessage, ServerResponse, TestRoute, unknown, unknown>.preHandler?: preHandlerHookHandler<Server, IncomingMessage, ServerResponse, TestRoute, unknown> | preHandlerHookHandler<Server, IncomingMessage, ServerResponse, TestRoute, unknown>[] | undefined

Type 'preHandlerAsyncHookHandler<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, {}, unknown>' is not assignable to type 'preHandlerHookHandler<Server, IncomingMessage, ServerResponse, TestRoute, unknown> | preHandlerHookHandler<Server, IncomingMessage, ServerResponse, TestRoute, unknown>[] | undefined'.
  Type 'preHandlerAsyncHookHandler<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, {}, unknown>' is not assignable to type 'preHandlerHookHandler<Server, IncomingMessage, ServerResponse, TestRoute, unknown>'.
    The 'this' types of each signature are incompatible.
      Type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>' is not assignable to type 'FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance>'.
        The types returned by 'after()' are incompatible between these types.
          Type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'.
            Type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance>'.
              Types of property 'register' are incompatible.
                Type 'FastifyRegister<FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>>' is not assignable to type 'FastifyRegister<FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance> & PromiseLike<...>>'.
                  Type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance> & PromiseLike<...>'.
                    Type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance> & PromiseLike<...>' is not assignable to type 'FastifyInstance<RawServerBase, IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse, FastifyLoggerInstance>'.
                      The types of 'addSchema(...).getDefaultRoute' are incompatible between these types.
                        Type 'DefaultRoute<IncomingMessage, ServerResponse>' is not assignable to type 'DefaultRoute<IncomingMessage | Http2ServerRequest, ServerResponse | Http2ServerResponse>'.
                          Type 'IncomingMessage | Http2ServerRequest' is not assignable to type 'IncomingMessage'.
                            Type 'Http2ServerRequest' is not assignable to type 'IncomingMessage'.ts(2322)
route.d.ts(43, 3): The expected type comes from property 'preHandler' which is declared here on type 'RouteOptions<Server, IncomingMessage, ServerResponse, TestRoute, unknown, FastifySchema>'
```

@anttti > As a temporary workaround you must surround your hook definitions with `OmitThisParameter<...>`, in your case :
```ts
// Here is a workaround :
const myHook: OmitThisParameter<preHandlerAsyncHookHandler<
  RawServerBase,
  RawRequestDefaultExpression<RawServerBase>,
  RawReplyDefaultExpression<RawServerBase>,
  {}
>> = async (_req, _res) => 'hello';
```

The PR https://github.com/fastify/fastify/pull/3143 seems to have introduced some hidden breaking changes and it seems to have an impact on the typescript fastify users. 😢

@mcollina > can you transfer this issue to the fastify repo please ?
